In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score


In [4]:
# loading the diabetes dataset to a pandas DataFrame
diabetes_dataset = pd.read_csv('/content/diabetes.csv')



In [5]:
pd.read_csv?


In [7]:
# printing the first 5 rows of the dataset
diabetes_dataset.head()

Glucose  BloodPressure  SkinThickness  Insulin   BMI  Outcome
0       85             50           50.0    190.0  90.0        1
1       60            100           26.0     80.0  26.7        0
2       90             90            3.0      2.0   0.0        0
3       70            110           30.0     70.0  30.6        0
4      100            115           39.0    160.0  60.6        1

In [8]:
# number of rows and Columns in this dataset
diabetes_dataset.shape

(52, 6)

In [10]:
# getting the statistical measures of the data
diabetes_dataset.describe()

Glucose  BloodPressure  SkinThickness     Insulin        BMI  \
count   52.000000      52.000000      52.000000   52.000000  52.000000   
mean    77.269231      86.269231      27.055769   98.598462  51.467308   
std     17.451463      19.970680      17.044698  108.214688  26.640326   
min     52.000000      34.000000       1.700000    0.000000   0.000000   
25%     60.000000      77.500000       4.000000   40.750000  23.000000   
50%     77.000000      90.000000      30.000000   67.000000  55.000000   
75%     91.000000      98.500000      41.000000   90.000000  75.250000   
max    109.000000     119.000000      50.000000  547.000000  98.000000   

         Outcome  
count  52.000000  
mean    0.153846  
std     0.364321  
min     0.000000  
25%     0.000000  
50%     0.000000  
75%     0.000000  
max     1.000000

In [11]:
diabetes_dataset['Outcome'].value_counts()

Outcome
0    44
1     8
Name: count, dtype: int64

In [12]:
diabetes_dataset.groupby('Outcome').mean()

Glucose  BloodPressure  SkinThickness  Insulin        BMI
Outcome                                                           
0           76.5      86.340909      25.270455   60.730  47.936364
1           81.5      85.875000      36.875000  306.875  70.887500

In [14]:
# separating the data and labels
X = diabetes_dataset.drop(columns = 'Outcome', axis=1)
Y = diabetes_dataset['Outcome']

In [15]:
print(X)


    Glucose  BloodPressure  SkinThickness  Insulin   BMI
0        85             50           50.0   190.00  90.0
1        60            100           26.0    80.00  26.7
2        90             90            3.0     2.00   0.0
3        70            110           30.0    70.00  30.6
4       100            115           39.0   160.00  60.6
5        60             80           28.0   180.00  20.5
6        70            105           30.0    80.00  28.8
7        60             90           40.0    90.00  80.0
8        60             70            6.0     9.00  14.0
9        70            110           30.0   120.00  30.0
10       70            100           25.0    90.00  40.0
11       80             59           45.0    67.00  50.0
12      100            118           18.0    50.00  50.0
13       57             45           34.0    45.00  89.0
14       80             56           45.0    58.00  98.0
15       56             34           46.0    89.00  89.0
16       56             88     

In [16]:
print(Y)

0     1
1     0
2     0
3     0
4     1
5     1
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    1
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    1
41    1
42    0
43    0
44    0
45    1
46    0
47    0
48    0
49    1
50    0
51    0
Name: Outcome, dtype: int64


In [17]:
scaler = StandardScaler()


In [18]:
scaler.fit(X)

StandardScaler()

In [19]:
standardized_data = scaler.transform(X)

In [20]:
print(standardized_data)


[[ 0.44730882 -1.83384269  1.35925448  0.85287204  1.4605163 ]
 [-0.99921225  0.69425434 -0.06254553 -0.17354312 -0.93876276]
 [ 0.73661304  0.18863493 -1.42510388 -0.90136478 -1.95078095]
 [-0.42060382  1.19987374  0.17442114 -0.26685359 -0.79093988]
 [ 1.31522146  1.45268345  0.70759614  0.57294064  0.3461592 ]
 [-0.99921225 -0.31698447  0.05593781  0.75956157 -1.17376324]
 [-0.42060382  0.94706404  0.17442114 -0.17354312 -0.85916583]
 [-0.99921225  0.18863493  0.76683781 -0.08023265  1.08148328]
 [-0.99921225 -0.82260388 -1.24737887 -0.83604745 -1.42013471]
 [-0.42060382  1.19987374  0.17442114  0.19969876 -0.81368186]
 [-0.42060382  0.69425434 -0.1217872  -0.08023265 -0.43464884]
 [ 0.15800461 -1.37878523  1.06304615 -0.29484673 -0.05561581]
 [ 1.31522146  1.60436927 -0.53647887 -0.45347452 -0.05561581]
 [-1.17279477 -2.08665239  0.41138781 -0.50012976  1.422613  ]
 [ 0.15800461 -1.53047105  1.06304615 -0.37882615  1.76374273]
 [-1.23065562 -2.64283374  1.12228782 -0.0895637   1.42

In [21]:
X = standardized_data
Y = diabetes_dataset['Outcome']

In [22]:
print(X)

[[ 0.44730882 -1.83384269  1.35925448  0.85287204  1.4605163 ]
 [-0.99921225  0.69425434 -0.06254553 -0.17354312 -0.93876276]
 [ 0.73661304  0.18863493 -1.42510388 -0.90136478 -1.95078095]
 [-0.42060382  1.19987374  0.17442114 -0.26685359 -0.79093988]
 [ 1.31522146  1.45268345  0.70759614  0.57294064  0.3461592 ]
 [-0.99921225 -0.31698447  0.05593781  0.75956157 -1.17376324]
 [-0.42060382  0.94706404  0.17442114 -0.17354312 -0.85916583]
 [-0.99921225  0.18863493  0.76683781 -0.08023265  1.08148328]
 [-0.99921225 -0.82260388 -1.24737887 -0.83604745 -1.42013471]
 [-0.42060382  1.19987374  0.17442114  0.19969876 -0.81368186]
 [-0.42060382  0.69425434 -0.1217872  -0.08023265 -0.43464884]
 [ 0.15800461 -1.37878523  1.06304615 -0.29484673 -0.05561581]
 [ 1.31522146  1.60436927 -0.53647887 -0.45347452 -0.05561581]
 [-1.17279477 -2.08665239  0.41138781 -0.50012976  1.422613  ]
 [ 0.15800461 -1.53047105  1.06304615 -0.37882615  1.76374273]
 [-1.23065562 -2.64283374  1.12228782 -0.0895637   1.42

In [23]:
print(Y)


0     1
1     0
2     0
3     0
4     1
5     1
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    1
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    1
41    1
42    0
43    0
44    0
45    1
46    0
47    0
48    0
49    1
50    0
51    0
Name: Outcome, dtype: int64


In [24]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, stratify=Y, random_state=2)

In [25]:
print(X.shape, X_train.shape, X_test.shape)


(52, 5) (41, 5) (11, 5)


In [29]:
classifier = svm.SVC(kernel='linear')

In [31]:
classifier.fit(X_train, Y_train)


SVC(kernel='linear')

In [32]:
# accuracy score on the training data
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [33]:
print('Accuracy score of the training data : ', training_data_accuracy)


Accuracy score of the training data :  1.0


In [35]:
input_data = (5,166,72,19,175)
# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# standardize the input data
std_data = scaler.transform(input_data_reshaped)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)

if (prediction[0] == 0):
  print('The person is not diabetic')
else:
  print('The person is diabetic')


[[-4.18155859  4.03134242  2.66257116 -0.74273698  4.68229704]]
[0]
The person is not diabetic


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
